runtime: python313

entrypoint: gunicorn -b :$PORT webmessage:app

env_variables:
  PGHOST: "ep-silent-violet-a26temai-pooler.eu-central-1.aws.neon.tech"
  PGUSER: "pucsp-dba"
  PGDATABASE: "pucsp"
  # Use Secret Manager for PGPASSWORD instead of plain text

automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_cpu_utilization: 0.65

instance_class: F2